### ISSUE TITLE
TetGen boundary layer meshes not flat at caps

### ISSUE THREAD

**Issue by ingridxlan** [SimVascular/SimVascular#931] opened 2021-08-30 22:57 UTC
When using TetGen to extrude boundary layers inward from the wall, the resulting cap meshes are no longer flat. I suspect this happens with any expanding or tapering vessels where the wall immediately adjacent to the cap isn't exactly normal to the cap (anything that isn't simply a straight cylinder). I've seen this with many patient-specific models at this point: a cerebral aneurysm, aorta, and the aortailiac demo model. I've also confirmed my suspicion with a straight vs. tapered cylinder comparison, though the non-flatness is very subtle in this tapered cylinder case (more apparent when the surface edges are turned off).

Attached are images of the straight vs. tapered cylinder comparison and outlets in the aortailiac demo model. As a more apparent example, I've also included an image of outlets from an aortic model.

![image](https://user-images.githubusercontent.com/43630965/131409049-83e3bb58-2beb-4a1c-bd4b-e81775d45c22.png)
![image](https://user-images.githubusercontent.com/43630965/131409063-1f347555-7386-4278-9537-6ae01577aa5f.png)
![image](https://user-images.githubusercontent.com/43630965/131409381-d0994e57-49b2-4d25-afcf-2d8bb8931c00.png)

For the aortailiac demo model, I used a global max edge size of 0.2 and BL meshing (extrude inward from the wall) with portion of edge size = 1.0, num layers = 3, and layer decreasing ratio = 0.5. I'm running SimVascular 2019.08.09 on my Ubuntu.

Since the issue of non-flat caps only arises for BL meshing, I've been able to address this issue on my end by subsequently projecting nodes on the caps to target planes, as defined by the corresponding non-BL cap meshes.

**Comment by ktbolt** [comment] 2021-08-30 23:27
@ingridxlan This is a known issue https://github.com/SimVascular/SimVascular/issues/806 but your discussion is much better so I will delete https://github.com/SimVascular/SimVascular/issues/806 and keep this one. 

That this occurs if  the wall immediately adjacent to the cap isn't exactly normal to the cap is an excellent observation!

If this is a big problem for you then I'll immediately start looking into a fix. If not then I'll put it off for later, not seen much discussion about this in the SV Forum.

**Comment by ingridxlan** [comment] 2021-08-30 23:43
@ktbolt Not a big problem at all. Certainly manageable with a little post-processing / scripted repair!

**Comment by ktbolt** [comment] 2021-09-20 23:27
The problem is that the point normals on the boundary between model caps and walls are not normal to the cap. The following image shows the point normals (green lines) pointing away from the cap surface (red). 

<img width="1070" alt="Screen Shot 2021-09-20 at 4 01 39 PM" src="https://user-images.githubusercontent.com/23109458/134087681-8b332f66-5bdd-4c94-b26c-7732139cb0be.png">

VMTK uses these normals to extruded surface polygons to create the boundary layer polygons so it seems that boundary layer meshing has never worked properly for caps.

**Comment by ktbolt** [comment] 2021-09-22 00:09
I've implemented a fix for this. The original mesh

<img width="1091" alt="Screen Shot 2021-09-21 at 4 59 48 PM" src="https://user-images.githubusercontent.com/23109458/134263126-7bec4fc7-615e-4f74-b8b1-d16df8e9c19f.png">

and with the fix

<img width="1201" alt="Screen Shot 2021-09-21 at 5 02 20 PM" src="https://user-images.githubusercontent.com/23109458/134263187-1d22d26d-449e-4dc3-b743-1b9090d692a6.png">

The current implementation does not mess around with the geometry but it may be too slow for complex meshes, uses `vtkPointLocator`.

**Comment by ktbolt** [comment] 2021-09-22 05:19
I've tested on several models with over 50 faces, the speed is very good, less than a second to set the boundary normals, meshes look good.

I tried testing on models with hundreds of faces but SV is unable to get past surface meshing stage for these guys.

I will clean up the code and integrate it into SV.

**Comment by ktbolt** [comment] 2021-09-22 21:27
I've simplified the code and merged into SV master.

**Closed by ktbolt** 2021-09-22 21:27 UTC
Labels: bug
