### ISSUE TITLE
Order of outlets wrong in 1D model

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#848] opened 2021-05-01 01:30 UTC
**Describe the bug**
The outlet names in the 1D Simulation plugin do not correspond to the correct outlets of the model. This happened to several students in BIOE285. In the following, I'm referring to this SimVascular project: https://drive.google.com/file/d/1-b-J6FpBkJ06g4wHinBljX1YM7I3_gNL/view?usp=sharing

When looking at the list of model caps and the outlets in the 1D modeling plugin (see screenshots below), the caps have the following order as given in the **left** column. The solver input file ```solver.in``` matches with that (**middle** column). However, when comparing the cap faces to the centerline (screenshot), it becomes apparent that the branches are sorted differently (**right** column):

Cap | Branch ID should (solver.in) | Branch ID is (centerline)
-- | -- | --
cap_L_Coronary_Artery | 1 | 5
cap_L_D1 | 5 | 6
cap_L_D2 | 6 | 9
cap_L_D3 | 9 | 10
cap_R_Coronary_Artery | 10 | 11
cap_R_D1 | 11 | 12
cap_R_D2 | 12 | 14
cap_R_D3 | 14 | 15
cap_Aorta_2 | 15 | 1

**To Reproduce**
1. Go to ```1D Simulation plugin```
2. Click on ```Calculate Centerlines```
3. Click on ```Create Files for Simulation```
3. Compare the order of outlets in Model plugin / 1D Simulation plugin / ```outlet_face_names.dat``` / ```solver.in``` to the one in ```centerlines.vtp```

**Expected behavior**
The order of outlets in Model plugin / 1D Simulation plugin / ```outlet_face_names.dat``` / ```solver.in``` should match with the one in ```centerlines.vtp```.

**Screenshots**
![image](https://user-images.githubusercontent.com/51269309/116766617-44fafd00-a9e0-11eb-8163-a9ae1c285a04.png)
List of faces in Model plugin

![image](https://user-images.githubusercontent.com/51269309/116766633-593efa00-a9e0-11eb-942b-e356cf9332e5.png)
List of faces in 1D Simulation plugin (order matches with Model)

![image](https://user-images.githubusercontent.com/51269309/116766747-f8fc8800-a9e0-11eb-865b-8d8e38e9db7d.png)
List of face names ```outlet_face_names.dat``` (order matches with Model)

![image](https://user-images.githubusercontent.com/51269309/116766664-7d024000-a9e0-11eb-8797-3cad1e6b4103.png)
Solver input file ```solver.in``` (order matches with Model)

![branchid](https://user-images.githubusercontent.com/51269309/116766680-973c1e00-a9e0-11eb-87a5-9cd4e1e92347.png)
Centerline ```centerlines.vtp``` and cap faces from ```Mesh``` folder (order does **not** match with Model).
Branch 1 connects to ```cap_Aorta_2 ``` instead of ```cap_L_Coronary_Artery``` (which connects to branch 5 instead).

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - SimVascular Version 2021.02.06
 - Medical Image Filetype [e.g. DICOM, MHA, ...]

**Additional context**
@ktbolt It looks like the outlet faces provided as input to the centerline extraction tool were shifted, with ```cap_Aorta_2``` jumping from last to first.  Is there a reason why  ```cap_Aorta_2``` is shown last? 

Possible explanations:
1. The input provided to the centerline extraction is sorted **alphabetically**, but is displayed differently in the GUI.
2. The users changed the names of outlets after generating the first 1D model but the list provided to the centerline extraction didn't get updated.

**Comment by mrp089** [comment] 2021-05-01 01:32
First brought up by @schwarz-e in https://github.com/SimVascular/svOneDSolver/issues/77

**Comment by ktbolt** [comment] 2021-05-10 22:50
This might be caused by a mismatch between model updates.

**Comment by mrp089** [comment] 2021-07-22 15:27
@ktbolt Did you have time to look at this? The same bug came up now in a different model

**Comment by ktbolt** [comment] 2021-07-22 17:58
@mrp089 I've not looked into this yet, will do so today.

**Comment by ktbolt** [comment] 2021-07-22 22:01
The code in `sv4guiModelUtils::CreateCenterlines()` removes the caps from the model, recaps the open model surface, and finds target points for the center of each cap. The order of the target  points will most likely not match the order of caps seen in the GUI.

**Comment by ktbolt** [comment] 2021-09-14 05:06
@mrp089 I looked at the SV code and see that the ordering of centerline target points does not follow the order of the face ID order. If I sort the  target points by face ID will this fix the problem?

**Comment by mrp089** [comment] 2021-09-14 09:54
As long as it's something "deterministic", I think it's fine. The numbering currently happens this way:

- we provide a list of coordinates that correspond to the outlet face centers
- `VMTK` generates a centerline for each outlet, all starting at the inlet
- `SimVascular` combines these centerlines and splits them into branches and junctions
-  `BranchId` starts at `0` at the inlet and then is incremented for all branches along centerline `0`
- This is repeated for each centerline, starting again at the inlet. If a branch already has an ID, it is skipped

For the relationship between outlet face ISs and centerline BranchIds, this means:
- There are (in general) more BranchIds than outlet face IDs due to interior branches
- Terminal BranchIds (at the outlets) are sorted the same way as outlet face IDs, but aren't identical

**Comment by ktbolt** [comment] 2021-09-14 18:56
I added sorting the centerline target IDs by the face ID they belong to. This will always produce the same ordering for the same face IDs.

I tested on the problem referenced here, looks good. 

@mrp089 I've merged the code into SV master. See if it pleases you!

**Closed by ktbolt** 2021-09-14 18:56 UTC
Labels: bug

**Comment by mrp089** [comment] 2021-10-01 00:16
Looks good!
